version: '3.1'
services:
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "4903:8025"
      - "4902:1025"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=omnibazaar_api

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 4004:80

    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root

  laravel.omnibazaar-api:
    container_name: omnibazaar-api
    image: docker.io/gurmesoft/laravel:8.6
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=omnibazaar_api
      - APP_ENV=local
      - APP_DEBUG=true
      - MAILHOG=mailhog
      - MAILHOG_PORT=1025

    ports:
      - 40000:9003
      - 4904:443
      - 4905:80

    volumes:
      - omnibazaar-api:/var/www/

    depends_on:
      - mariadb
      - phpmyadmin

volumes:
  omnibazaar-api:
    driver: local
networks:
  default:
    external:
      name: gurme-network
