version: '3.1'
services:
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "2803:8025"
      - "2802:1025"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=kargo.shopify

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 2801:80

    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root

  laravel.shopify:
    image: docker.io/gurmesoft/laravel:8.6
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=kargo.shopify
      - APP_ENV=local
      - APP_DEBUG=true
      - MAILHOG=mailhog
      - MAILHOG_PORT=1025

    ports:
      - 443:443
      - 28000:80
      - 29000:9003

    volumes:
      - kargo.shopify:/var/www/

    depends_on:
      - mariadb
      - phpmyadmin

volumes:
  kargo.shopify:
    driver: local