version: '3.1'
services:
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "4006:8025"
      - "4005:1025"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=iyzibazaar
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 4004:80

    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root

  wordpress.iyzibazaar:
    container_name: iyzibazaar
    image: docker.io/gurmesoft/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=iyzibazaar
      - WORDPRESS_HOME=iyzibazaar.gurmeapps.local
      - WORDPRESS_TITLE= iyzibazaar
      - WORDPRESS_ADMIN=admin@gurmesoft.com
      - WORDPRESS_EMAIL=admin@gurmesoft.com
      - WORDPRESS_PASSWORD=adminadmin
      - MAILHOG=mailhog
      - MAILHOG_PORT=4025

    ports:
      - 4003:9003
      - 4001:80

    volumes:
      - iyzibazaar:/var/www

    depends_on:
      - mariadb
      - phpmyadmin
volumes:
  iyzibazaar:
  db: