version: '2.1'

volumes:
  db-data:
  vendor:
  var:

services:
  mysql:
    image: mysql:5
    ports:
      - "3004:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestabazaar
      MYSQL_DATABASE: prestabazaar
    restart: always
  presta.prestabazaar:
    image: docker.io/gurmesoft/prestashop
    container_name: prestabazaar
    environment:
      PS_INSTALL_AUTO: 1
      PS_SHOP_DEFAULT: 1
      DB_PASSWD: prestabazaar
      DB_NAME: prestabazaar
      DB_SERVER: mysql
      DB_PREFIX: ps
      PS_COUNTRY: tr
      PS_LANGUAGE: tr
      PS_DEV_MODE: 1
      PS_DOMAIN: prestabazaar.gurmeapps.local
      PS_ENABLE_SSL: 1
      ADMIN_PASSWD: adminadmin
      ADMIN_MAIL: admin@gurmesoft.com
    ports:
      - "3001:80"
networks:
  gurme-network: