version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9080:9080
    environment:
      - PMA_ARBITRARY=1