version: '3.1'
services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=1
networks:
  default:
    external:
      name: gurme-network