version: '2.1'

volumes:
  db-data:
  vendor:
  var:

services:
  mysql:
    image: mysql:5
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
  prestashop:
    image: docker.io/gurmesoft/prestashop
    environment:
      PS_INSTALL_AUTO: 1
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_SERVER: mysql
      DB_PREFIX: ps
      PS_DOMAIN: localhost:8002
      PS_COUNTRY: tr
      PS_LANGUAGE: tr
      PS_DEV_MODE: 1
      ADMIN_PASSWD: admin
    ports:
      - "8002:80"