# Use root/example as user/password credentials
version: "3.1"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_USER: "root"
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "gurmesoft"

    volumes:
      - ./datadir:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - gurme-network
networks:
  gurme-network:
    external: true
