# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: "root"
      MARIADB_ROOT_PASSWORD: ""
      MARIADB_DATABASE: "gurmesoft"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: "gurmesoft"
      
    volumes:
      - ./datadir:/var/lib/mysql
    ports:
      - "3306:3306"